$Type: Projects$ModuleSettings
BasedOnVersion: ""
ExportLevel: Source
JarDependencies:
- $Type: Projects$JarDependency
  ArtifactId: guava
  GroupId: com.google.guava
  IsIncluded: true
  Version: 32.0.1-jre
- $Type: Projects$JarDependency
  ArtifactId: owasp-java-html-sanitizer
  GroupId: com.googlecode.owasp-java-html-sanitizer
  IsIncluded: true
  Version: "20211018.2"
- $Type: Projects$JarDependency
  ArtifactId: commons-io
  GroupId: commons-io
  IsIncluded: true
  Version: 2.11.0
- $Type: Projects$JarDependency
  ArtifactId: pdfbox
  GroupId: org.apache.pdfbox
  IsIncluded: true
  Version: 2.0.30
- $Type: Projects$JarDependency
  ArtifactId: commons-lang3
  GroupId: org.apache.commons
  IsIncluded: true
  Version: 3.12.0
- $Type: Projects$JarDependency
  ArtifactId: commons-text
  GroupId: org.apache.commons
  IsIncluded: true
  Version: 1.10.0
ProtectedModuleType: AddOn
SolutionIdentifier: ""
Version: 1.0.0
