$Type: JavaActions$JavaAction
ActionDefaultReturnName: ReturnValueName
Documentation: Returns the runtime URL of this application.
Excluded: false
ExportLevel: Hidden
JavaReturnType:
  $Type: CodeActions$StringType
MicroflowActionInfo:
  $Type: CodeActions$MicroflowActionInfo
  Caption: Get application URL
  Category: Misc
  IconData:
    Data: ""
    Subtype: 0
  IconDataDark:
    Data: ""
    Subtype: 0
  ImageDataDark:
    Data: ""
    Subtype: 0
Name: GetApplicationUrl
Parameters: null
TypeParameters: null
