name: Build and Test

on:
  push:
    branches:
    - "*"
  pull_request:
    branches: [ main ]

jobs:

  Policies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test Policies
      run: ./run-policy-tests.sh

  CLI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build
      run: go build -o bin/mendix-cli "./cmd/mendix-cli"

    - name: Test
      run: go test -v ./...

    - name: xunit-report
      run: ./bin/mendix-cli lint --xunit-report report.xml || true

    - name: Process xunit-report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Lint Test Report
        path: report.xml
        reporter: java-junit
