name: Continuous Integration

on:
  push:
    branches:
    - "*"
  pull_request:
    branches: [ main ]

jobs:

  CLI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build
      run: go build -o bin/mxlint "./cmd/mxlint"

    - name: Test
      run: go test -v ./...

    - name: Test subcommand export-model
      run: |
        bin/mxlint export-model --mode advanced -i resources/app
        git diff --exit-code modelsource 

    - name: Test subcommand lint
      run: ./bin/mxlint lint --xunit-report report.xml --policies ./resources/policies

    - name: Process xunit-report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Lint Test Report
        path: report.xml
        reporter: java-junit
